# Invoke the backport bot whenever we merge into dev.

name: backport-on-merge

on:
  push:
    branches:
      - dev

env:
  SCRIPT_DIR: "${{ github.workspace }}/.github/workflows/scripts/backport-command"
  PR_NUMBER: ${{ github.event.number }}

jobs:
  backport-on-merge:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Backport On Merge
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
        id: extract_required_backports_from_pr_body
        run: $SCRIPT_DIR/backport_on_merge.sh
        shell: bash
